# ruff.toml
line-length = 200
target-version = "py312"

# Habilita reglas equivalentes a Flake8, isort, pyupgrade, etc.



[lint]
select = ["E4", "E7", "E9", "F", "I"]
extend-select = ["E", "F", "I", "UP", "B", "W"]
ignore = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
fixable = ["ALL"]
unfixable = []